import { StyleSheet } from "react-native";

export const colors = {
  bg: "#FDFBF7",
  surface: "#FFFFFF",
  alt: "#FFE66D",
  primary: "#FF6B6B",
  secondary: "#4ECDC4",
  yellow: "#FFE66D",
  orange: "#FF9F1C",
  text: "#1A1A1A",
  textSecondary: "#4A4A4A",
  textDisabled: "#A0A0A0",
  border: "#000000",
  borderLight: "#E5E5E5",
  success: "#2D6A4F",
  warning: "#FF9F1C",
  error: "#E63946",
  verified: "#3A86FF",
  purple: "#C9A0FF",
};

export const brutal = StyleSheet.create({
  card: {
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 6,
    padding: 16,
  },
  cardLarge: {
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    padding: 20,
  },
  buttonPrimary: {
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 6,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  buttonSecondary: {
    backgroundColor: colors.yellow,
    borderWidth: 2,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 6,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  buttonOutline: {
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  buttonText: {
    color: colors.text,
    fontWeight: "900",
    fontSize: 15,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  input: {
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 16,
    fontWeight: "500",
    color: colors.text,
  },
  badge: {
    backgroundColor: colors.secondary,
    borderWidth: 2,
    borderColor: colors.border,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  badgeText: {
    color: colors.text,
    fontWeight: "800",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  h1: {
    fontSize: 32,
    fontWeight: "900",
    color: colors.text,
    letterSpacing: -1,
  },
  h2: {
    fontSize: 26,
    fontWeight: "900",
    color: colors.text,
    letterSpacing: -0.5,
  },
  h3: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.text,
  },
  body: {
    fontSize: 15,
    color: colors.text,
    fontWeight: "500",
    lineHeight: 22,
  },
  caption: {
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
    color: colors.textSecondary,
  },
});
